name: Sync Slack Daily Reports to Notion

on:
  schedule:
    # 毎日 20:05 JST 実行（= 11:05 UTC）
    - cron: "5 11 * * *"
  workflow_dispatch: {}
  push:
    branches: [ master, main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sync
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
          LOOKBACK_DAYS: "30"
        run: |
          python sync_daily_reports.py
